src/Admin/AdminConsole/Models/OrganizationViewModel.cs
using Bit.Core.AdminConsole.Entities;
using Bit.Core.AdminConsole.Entities.Provider;
using Bit.Core.Entities;
using Bit.Core.Enums;
using Bit.Core.Models.Data.Organizations.OrganizationUsers;
using Bit.Core.Vault.Entities;

namespace Bit.Admin.AdminConsole.Models;

public class OrganizationViewModel
{
    public OrganizationViewModel()
    {
    }

    public OrganizationViewModel(Organization org, Provider provider, IEnumerable<OrganizationConnection> connections,
        IEnumerable<OrganizationUserUserDetails> orgUsers, IEnumerable<Cipher> ciphers,
        IEnumerable<Collection> collections,
        IEnumerable<Group> groups, IEnumerable<Policy> policies, int secretsCount, int projectCount,
        int serviceAccountsCount,
        int occupiedSmSeatsCount)

    {
        Organization = org;
        Provider = provider;
        Connections = connections ?? Enumerable.Empty<OrganizationConnection>();
        HasPublicPrivateKeys = org.PublicKey != null && org.PrivateKey != null;
        UserInvitedCount = orgUsers.Count(u => u.Status == OrganizationUserStatusType.Invited);
        UserAcceptedCount = orgUsers.Count(u => u.Status == OrganizationUserStatusType.Accepted);
        UserConfirmedCount = orgUsers.Count(u => u.Status == OrganizationUserStatusType.Confirmed);
        OccupiedSeatCount = UserInvitedCount + UserAcceptedCount + UserConfirmedCount;
        CipherCount = ciphers.Count();
        CollectionCount = collections.Count();
        GroupCount = groups?.Count() ?? 0;
        PolicyCount = policies?.Count() ?? 0;
        var organizationUserStatus = org.Status == OrganizationStatusType.Pending
            ? OrganizationUserStatusType.Invited
            : OrganizationUserStatusType.Confirmed;
        Owners = string.Join(", ",
            orgUsers
                .Where(u => u.Type == OrganizationUserType.Owner && u.Status == organizationUserStatus)
                .Select(u => u.Email));
        Admins = string.Join(", ",
            orgUsers
                .Where(u => u.Type == OrganizationUserType.Admin && u.Status == organizationUserStatus)
                .Select(u => u.Email));
        SecretsCount = secretsCount;
        ProjectsCount = projectCount;
        ServiceAccountsCount = serviceAccountsCount;
        OccupiedSmSeatsCount = occupiedSmSeatsCount;
    }

    public Organization Organization { get; set; }
    public Provider Provider { get; set; }
    public IEnumerable<OrganizationConnection> Connections { get; set; }
    public string Owners { get; set; }
    public string Admins { get; set; }
    public int UserInvitedCount { get; set; }
    public int UserConfirmedCount { get; set; }
    public int UserAcceptedCount { get; set; }
    public int OccupiedSeatCount { get; set; }
    public int CipherCount { get; set; }
    public int CollectionCount { get; set; }
    public int GroupCount { get; set; }
    public int PolicyCount { get; set; }
    public bool HasPublicPrivateKeys { get; set; }
    public int SecretsCount { get; set; }
    public int ProjectsCount { get; set; }
    public int ServiceAccountsCount { get; set; }
    public int OccupiedSmSeatsCount { get; set; }
    public bool UseSecretsManager => Organization.UseSecretsManager;
    public bool UseRiskInsights => Organization.UseRiskInsights;
}

src/Admin/AdminConsole/Controllers/OrganizationsController.cs
using System.Net;
using Bit.Admin.AdminConsole.Models;
using Bit.Admin.Enums;
using Bit.Admin.Services;
using Bit.Admin.Utilities;
using Bit.Core;
using Bit.Core.AdminConsole.Entities;
using Bit.Core.AdminConsole.Enums.Provider;
using Bit.Core.AdminConsole.Providers.Interfaces;
using Bit.Core.AdminConsole.Repositories;
using Bit.Core.Billing.Enums;
using Bit.Core.Billing.Extensions;
using Bit.Core.Billing.Services;
using Bit.Core.Context;
using Bit.Core.Enums;
using Bit.Core.Models.OrganizationConnectionConfigs;
using Bit.Core.OrganizationFeatures.OrganizationSponsorships.FamiliesForEnterprise.Interfaces;
using Bit.Core.Repositories;
using Bit.Core.SecretsManager.Repositories;
using Bit.Core.Services;
using Bit.Core.Settings;
using Bit.Core.Tools.Enums;
using Bit.Core.Tools.Models.Business;
using Bit.Core.Tools.Services;
using Bit.Core.Utilities;
using Bit.Core.Vault.Repositories;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Bit.Admin.AdminConsole.Controllers;

[Authorize]
public class OrganizationsController : Controller
{
    private readonly IOrganizationService _organizationService;
    private readonly IOrganizationRepository _organizationRepository;
    private readonly IOrganizationUserRepository _organizationUserRepository;
    private readonly IOrganizationConnectionRepository _organizationConnectionRepository;
    private readonly ISelfHostedSyncSponsorshipsCommand _syncSponsorshipsCommand;
    private readonly ICipherRepository _cipherRepository;
    private readonly ICollectionRepository _collectionRepository;
    private readonly IGroupRepository _groupRepository;
    private readonly IPolicyRepository _policyRepository;
    private readonly IPaymentService _paymentService;
    private readonly IApplicationCacheService _applicationCacheService;
    private readonly GlobalSettings _globalSettings;
    private readonly IReferenceEventService _referenceEventService;
    private readonly IUserService _userService;
    private readonly IProviderRepository _providerRepository;
    private readonly ILogger<OrganizationsController> _logger;
    private readonly IAccessControlService _accessControlService;
    private readonly ICurrentContext _currentContext;
    private readonly ISecretRepository _secretRepository;
    private readonly IProjectRepository _projectRepository;
    private readonly IServiceAccountRepository _serviceAccountRepository;
    private readonly IProviderOrganizationRepository _providerOrganizationRepository;
    private readonly IRemoveOrganizationFromProviderCommand _removeOrganizationFromProviderCommand;
    private readonly IProviderBillingService _providerBillingService;
    private readonly IFeatureService _featureService;

    public OrganizationsController(
        IOrganizationService organizationService,
        IOrganizationRepository organizationRepository,
        IOrganizationUserRepository organizationUserRepository,
        IOrganizationConnectionRepository organizationConnectionRepository,
        ISelfHostedSyncSponsorshipsCommand syncSponsorshipsCommand,
        ICipherRepository cipherRepository,
        ICollectionRepository collectionRepository,
        IGroupRepository groupRepository,
        IPolicyRepository policyRepository,
        IPaymentService paymentService,
        IApplicationCacheService applicationCacheService,
        GlobalSettings globalSettings,
        IReferenceEventService referenceEventService,
        IUserService userService,
        IProviderRepository providerRepository,
        ILogger<OrganizationsController> logger,
        IAccessControlService accessControlService,
        ICurrentContext currentContext,
        ISecretRepository secretRepository,
        IProjectRepository projectRepository,
        IServiceAccountRepository serviceAccountRepository,
        IProviderOrganizationRepository providerOrganizationRepository,
        IRemoveOrganizationFromProviderCommand removeOrganizationFromProviderCommand,
        IProviderBillingService providerBillingService,
        IFeatureService featureService)
    {
        _organizationService = organizationService;
        _organizationRepository = organizationRepository;
        _organizationUserRepository = organizationUserRepository;
        _organizationConnectionRepository = organizationConnectionRepository;
        _syncSponsorshipsCommand = syncSponsorshipsCommand;
        _cipherRepository = cipherRepository;
        _collectionRepository = collectionRepository;
        _groupRepository = groupRepository;
        _policyRepository = policyRepository;
        _paymentService = paymentService;
        _applicationCacheService = applicationCacheService;
        _globalSettings = globalSettings;
        _referenceEventService = referenceEventService;
        _userService = userService;
        _providerRepository = providerRepository;
        _logger = logger;
        _accessControlService = accessControlService;
        _currentContext = currentContext;
        _secretRepository = secretRepository;
        _projectRepository = projectRepository;
        _serviceAccountRepository = serviceAccountRepository;
        _providerOrganizationRepository = providerOrganizationRepository;
        _removeOrganizationFromProviderCommand = removeOrganizationFromProviderCommand;
        _providerBillingService = providerBillingService;
        _featureService = featureService;
    }

    [RequirePermission(Permission.Org_List_View)]
    public async Task<IActionResult> Index(string name = null, string userEmail = null, bool? paid = null,
        int page = 1, int count = 25)
    {
        if (page < 1)
        {
            page = 1;
        }

        if (count < 1)
        {
            count = 1;
        }

        var encodedName = WebUtility.HtmlEncode(name);
        var skip = (page - 1) * count;
        var organizations = await _organizationRepository.SearchAsync(encodedName, userEmail, paid, skip, count);
        return View(new OrganizationsModel
        {
            Items = organizations as List<Organization>,
            Name = string.IsNullOrWhiteSpace(name) ? null : name,
            UserEmail = string.IsNullOrWhiteSpace(userEmail) ? null : userEmail,
            Paid = paid,
            Page = page,
            Count = count,
            Action = _globalSettings.SelfHosted ? "View" : "Edit",
            SelfHosted = _globalSettings.SelfHosted
        });
    }

    public async Task<IActionResult> View(Guid id)
    {
        var organization = await _organizationRepository.GetByIdAsync(id);
        if (organization == null)
        {
            return RedirectToAction("Index");
        }

        var provider = await _providerRepository.GetByOrganizationIdAsync(id);
        var ciphers = await _cipherRepository.GetManyByOrganizationIdAsync(id);
        var collections = await _collectionRepository.GetManyByOrganizationIdAsync(id);
        IEnumerable<Group> groups = null;
        if (organization.UseGroups)
        {
            groups = await _groupRepository.GetManyByOrganizationIdAsync(id);
        }
        IEnumerable<Policy> policies = null;
        if (organization.UsePolicies)
        {
            policies = await _policyRepository.GetManyByOrganizationIdAsync(id);
        }
        var users = await _organizationUserRepository.GetManyDetailsByOrganizationAsync(id);
        var billingSyncConnection = _globalSettings.EnableCloudCommunication ? await _organizationConnectionRepository.GetByOrganizationIdTypeAsync(id, OrganizationConnectionType.CloudBillingSync) : null;
        var secrets = organization.UseSecretsManager ? await _secretRepository.GetSecretsCountByOrganizationIdAsync(id) : -1;
        var projects = organization.UseSecretsManager ? await _projectRepository.GetProjectCountByOrganizationIdAsync(id) : -1;
        var serviceAccounts = organization.UseSecretsManager ? await _serviceAccountRepository.GetServiceAccountCountByOrganizationIdAsync(id) : -1;
        var smSeats = organization.UseSecretsManager
            ? await _organizationUserRepository.GetOccupiedSmSeatCountByOrganizationIdAsync(organization.Id)
            : -1;
        return View(new OrganizationViewModel(organization, provider, billingSyncConnection, users, ciphers, collections, groups, policies,
            secrets, projects, serviceAccounts, smSeats));
    }

    [SelfHosted(NotSelfHostedOnly = true)]
    public async Task<IActionResult> Edit(Guid id)
    {
        var organization = await _organizationRepository.GetByIdAsync(id);
        if (organization == null)
        {
            return RedirectToAction("Index");
        }

        var provider = await _providerRepository.GetByOrganizationIdAsync(id);
        var ciphers = await _cipherRepository.GetManyByOrganizationIdAsync(id);
        var collections = await _collectionRepository.GetManyByOrganizationIdAsync(id);
        IEnumerable<Group> groups = null;
        if (organization.UseGroups)
        {
            groups = await _groupRepository.GetManyByOrganizationIdAsync(id);
        }
        IEnumerable<Policy> policies = null;
        if (organization.UsePolicies)
        {
            policies = await _policyRepository.GetManyByOrganizationIdAsync(id);
        }
        var users = await _organizationUserRepository.GetManyDetailsByOrganizationAsync(id);
        var billingInfo = await _paymentService.GetBillingAsync(organization);
        var billingHistoryInfo = await _paymentService.GetBillingHistoryAsync(organization);
        var billingSyncConnection = _globalSettings.EnableCloudCommunication ? await _organizationConnectionRepository.GetByOrganizationIdTypeAsync(id, OrganizationConnectionType.CloudBillingSync) : null;
        var secrets = organization.UseSecretsManager ? await _secretRepository.GetSecretsCountByOrganizationIdAsync(id) : -1;
        var projects = organization.UseSecretsManager ? await _projectRepository.GetProjectCountByOrganizationIdAsync(id) : -1;

src/Admin/AdminConsole/Views/Shared/_OrganizationFormScripts.cshtml
@inject IWebHostEnvironment HostingEnvironment
@using Bit.Admin.Utilities
@using Bit.Core.Billing.Enums
@using Bit.Core.Enums
@using Bit.Core.Utilities
@model OrganizationEditModel

<script>
    (() => {
        document.getElementById('@(nameof(Model.PlanType))').addEventListener('change', () => {
            const selectEl = document.getElementById('@(nameof(Model.PlanType))');
            const selectText = selectEl.options[selectEl.selectedIndex].text;
            document.getElementById('@(nameof(Model.Plan))').value = selectText;
            togglePlanFeatures(selectEl.options[selectEl.selectedIndex].value);
        });
        document.getElementById('gateway-customer-link')?.addEventListener('click', () => {
            const gateway = document.getElementById('@(nameof(Model.Gateway))');
            const customerId = document.getElementById('@(nameof(Model.GatewayCustomerId))');
            if (!gateway || gateway.value === '' || !customerId || customerId.value === '') {
                return;
            }
            if (gateway.value === '@((byte)GatewayType.Stripe)') {
                const url = `@(HostingEnvironment.GetStripeUrl())/customers/${customerId.value}/`;
                window.open(url, '_blank');
            } else if (gateway.value === '@((byte)GatewayType.Braintree)') {
                const url = `@(HostingEnvironment.GetBraintreeMerchantUrl())/@Model.BraintreeMerchantId/${customerId.value}`;
                window.open(url, '_blank');
            }
        });
        document.getElementById('gateway-subscription-link')?.addEventListener('click', () => {
            const gateway = document.getElementById('@(nameof(Model.Gateway))');
            const subId = document.getElementById('@(nameof(Model.GatewaySubscriptionId))');
            if (!gateway || gateway.value === '' || !subId || subId.value === '') {
                return;
            }
            if (gateway.value === '@((byte)GatewayType.Stripe)') {
                const url = `@(HostingEnvironment.GetStripeUrl())/subscriptions/${subId.value}/`;
                window.open(url, '_blank');
            } else if (gateway.value === '@((byte)GatewayType.Braintree)') {
                const url = `@(HostingEnvironment.GetBraintreeMerchantUrl())/@Model.BraintreeMerchantId/subscriptions/${subId.value}`;
                window.open(url, '_blank');
            }
        });
        document.getElementById('@(nameof(Model.UseSecretsManager))').addEventListener('change', (event) => {
            document.getElementById('organization-secrets-configuration').hidden = !event.target.checked;

            if (event.target.checked) {
                setInitialSecretsManagerConfiguration();
                return;
            }

            clearSecretsManagerConfiguration();
        });
    })();

    function togglePlanFeatures(planType) {
        const plan = getPlan(planType);

        if (!plan) {
            return;
        }

        console.log(plan);

        document.getElementById('@(nameof(Model.SelfHost))').checked = plan.hasSelfHost;

        document.getElementById('@(nameof(Model.Use2fa))').checked = plan.has2fa;
        document.getElementById('@(nameof(Model.UseApi))').checked = plan.hasApi;
        document.getElementById('@(nameof(Model.UseGroups))').checked = plan.hasGroups;
        document.getElementById('@(nameof(Model.UsePolicies))').checked = plan.hasPolicies;
        document.getElementById('@(nameof(Model.UseSso))').checked = plan.hasSso;
        document.getElementById('@(nameof(Model.UseScim))').checked = plan.hasScim;
        document.getElementById('@(nameof(Model.UseDirectory))').checked = plan.hasDirectory;
        document.getElementById('@(nameof(Model.UseEvents))').checked = plan.hasEvents;
        document.getElementById('@(nameof(Model.UseResetPassword))').checked = plan.hasResetPassword;
        document.getElementById('@(nameof(Model.UseCustomPermissions))').checked = plan.hasCustomPermissions;
        // use key connector is intentionally omitted

        document.getElementById('@(nameof(Model.UseTotp))').checked = plan.hasTotp;
        document.getElementById('@(nameof(Model.UsersGetPremium))').checked = plan.usersGetPremium;

        document.getElementById('@(nameof(Model.MaxStorageGb))').value =
            document.getElementById('@(nameof(Model.MaxStorageGb))').value ||
            plan.passwordManager.baseStorageGb ||
            1;
        document.getElementById('@(nameof(Model.Seats))').value = document.getElementById('@(nameof(Model.Seats))').value ||
            plan.passwordManager.baseSeats ||
            1;
    }

    function unlinkProvider(id) {
        if (confirm('Are you sure you want to unlink this organization from its provider?')) {
            $.ajax({
                type: "POST",
                url: `@Url.Action("UnlinkOrganizationFromProvider", "Organizations")?id=${id}`,
                dataType: 'json',
                contentType: false,
                processData: false,
                success: function (response) {
                    alert("Successfully unlinked provider");
                    window.location.href = `@Url.Action("Edit", "Organizations")?id=${id}`;
                },
                error: function (response) {
                    alert("Error!");
                }
            });
        }
        return false;
    }

    /***
    * Set Secrets Manager values based on current usage (for migrating from SM beta or reinstating an old subscription)
    */
    function setInitialSecretsManagerConfiguration() {
        const planType = document.getElementById('@(nameof(Model.PlanType))').value;

        // Seats
        document.getElementById('@(nameof(Model.SmSeats))').value = Math.max(@Model.OccupiedSmSeatsCount, 1);

        // Service accounts
        const baseServiceAccounts = getPlan(planType)?.secretsManager?.baseServiceAccount ?? 0;
        if (planType !== '@((byte)PlanType.Free)' && @Model.ServiceAccountsCount > baseServiceAccounts) {
            document.getElementById('@(nameof(Model.SmServiceAccounts))').value = @Model.ServiceAccountsCount;
        } else {
            document.getElementById('@(nameof(Model.SmServiceAccounts))').value = baseServiceAccounts;
        }

        // Clear autoscale values (no defaults)
        document.getElementById('@(nameof(Model.MaxAutoscaleSmSeats))').value = '';
        document.getElementById('@(nameof(Model.MaxAutoscaleSmServiceAccounts))').value = '';
    }

    function clearSecretsManagerConfiguration() {
        document.getElementById('@(nameof(Model.SmSeats))').value = '';
        document.getElementById('@(nameof(Model.SmServiceAccounts))').value = '';
        document.getElementById('@(nameof(Model.MaxAutoscaleSmSeats))').value = '';
        document.getElementById('@(nameof(Model.MaxAutoscaleSmServiceAccounts))').value = '';
    }

    function getPlan(planType) {
        const plans = @Html.Raw(Json.Serialize(Model.GetPlansHelper()));
        return plans.find(p => p.type == planType);
    }
</script>